[package]
name = "yew-todo"
version = "0.1.0"
edition = "2021"

[dependencies]
yew = { version = "0.19" }
gloo = "0.6"
serde = "1.0"
serde_json = "1.0"
wasm-bindgen = "0.2"
web-sys = { version = "0.3", features = ["HtmlInputElement"] }

stylist = { version = "0.10", features = ["yew"] }
